network:
    version: 2
    renderer: networkd
    ethernets:
        enp3s0:
            addresses:
                - 10.0.0.2/24
            nameservers:
                addresses: [8.8.8.8, 1.1.1.1]
            routes:
                - to: default
                  via: 10.0.0.1
